spring.application.name=tech-challenge-fase02

spring.mvc.problemdetails.enabled=true

spring.datasource.url=jdbc:postgresql://localhost:5432/tech_challenge_fase02
spring.datasource.username=postgres
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.open-in-view=false

spring.flyway.enabled=true

jwt.secret=${JWT_SECRET:dGVjaC1jaGFsbGVuZ2UtZmFzZTAyLWp3dC1zZWNyZXQta2V5LWZpYXAtMjAyNS10ZWNoY2hhbGxlbmdl}
jwt.expiration-ms=${JWT_EXPIRATION_MS:86400000}

